variable "ecr_registry" {}
variable "bucket" {}
variable "acl" {}
variable "key" {}
variable "infra_statefile_key" {}
variable "region" {}
variable "encrypt" {}
variable "dynamodb_table" {}
variable "fqdn" {}
variable "image_tag" {}
variable "domain" {}
variable "environment" {}
variable "vpc_id" {}
variable "azs" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "certificate_arn" {}
variable "name" {}
